name: SSH Pull and Build

on: 
  push: 
   branches:
    - main
    - gh-actions/**

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up Node.js v10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Installing dependencies
      run: npm ci
    - name: Building Vue App
      run: npm run build
    - name: Preparing code to sync
      run: npm prune --production
    - name: Syncing code to Toolforge
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "./"
        target: "www/js"
        rm: true
    - name: Executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          ls www/js -la